"use client"

import { Product } from "@/data/products"
import { TeaContent } from "@/data/teaContent"
import { useCart } from "@/lib/cart-context"
import { useCartDrawer } from "@/lib/cart-store"
import ProductGallery from "./ProductGallery"
import { useEffect, useState, useMemo } from "react"
// Cached prices generated by scripts/fetch_prices.js
import cachedPricesJson from "@/data/prices.json"
const cachedPrices: Record<string, { unit_amount: number | null }> = cachedPricesJson as unknown as Record<string, { unit_amount: number | null }>

type PriceMap = Record<string, number>

type Props = {
    product: Product
    content: TeaContent
}

export default function ProductClient({ product, content }: Props) {
    const { addItem } = useCart()
    const { open } = useCartDrawer()

    const [selectedVariantId, setSelectedVariantId] = useState<string | null>(
    product.variants[0]?.id ?? null
    )

const [prices, setPrices] = useState<PriceMap>({})
const [loadingPrices, setLoadingPrices] = useState(true)

const priceIds = useMemo(() => product.variants.map((v) => v.stripePriceId).filter(Boolean), [product])

useEffect(() => {
        if (priceIds.length === 0) {
            // ensure state updates happen asynchronously to avoid cascading sync renders
            Promise.resolve().then(() => {
                setPrices({})
                setLoadingPrices(false)
            })
            return
        }

        let cancelled = false

        // set loading state asynchronously to avoid sync setState-in-effect
        Promise.resolve().then(() => setLoadingPrices(true))
        fetch("/api/prices", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ priceIds }),
        })
            .then((res) => res.json())
            .then((data) => {
                if (!cancelled) setPrices(data)
            })
            .catch(() => {
                if (!cancelled) setPrices({})
            })
            .finally(() => {
                if (!cancelled) setLoadingPrices(false)
            })

        return () => {
            cancelled = true
        }
}, [priceIds])

const selectedVariant =
    product.variants.length > 0
      ? product.variants.find((v) => v.id === selectedVariantId) ?? product.variants[0]
      : null

const selectedPrice =
    selectedVariant && prices[selectedVariant.stripePriceId]

const handleAdd = () => {
    if (!selectedVariant || !selectedPrice) return

    addItem({
    variantId: selectedVariant.id,
    productId: product.id,
    slug: product.slug,
    title: content.displayName,
    variantLabel: selectedVariant.label,
    weightGrams: selectedVariant.weightGrams,
    price: selectedPrice,
    stripePriceId: selectedVariant.stripePriceId,
    image: product.images.preview,
    quantity: 1,
    })

    open()
}

const hasFlavor =
    Array.isArray(content.flavorProfile) &&
    content.flavorProfile.length > 0

const hasEffect = Boolean(content.effect)

const hasBrewing = Boolean(content.brewing)

return (
    <main style={{ maxWidth: 1120, margin: "0 auto", padding: "clamp(32px, 5vw, 64px) clamp(16px, 4vw, 24px)" }}>
      {/* TOP */}
    <div
        style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 400px), 1fr))",
        gap: "clamp(32px, 6vw, 96px)",
        marginBottom: "clamp(64px, 10vw, 140px)",
        }}
    >
        <ProductGallery
          previewImage={product.images.preview}
          galleryImages={product.images.gallery}
          productName={content.displayName}
        />

        <div>
        <p
            style={{
            textTransform: "uppercase",
            letterSpacing: "0.32em",
            fontSize: 12,
            color: "#8a8883",
            marginBottom: 14,
            }}
        >
            {product.category}
        </p>

        <h1 style={{ fontSize: "clamp(28px, 5vw, 48px)", fontWeight: 500, marginBottom: 14 }}>
            {content.displayName}
        </h1>

        <p style={{ fontSize: 18, color: "#777", marginBottom: 24 }}>
            {content.tagline}
        </p>

        <p
            style={{
            fontSize: 17,
            lineHeight: 1.75,
            color: "#555",
            marginBottom: 42,
            maxWidth: 520,
            }}
        >
            {content.description}
        </p>

          {/* VARIANTS */}
        {product.variants.length > 1 && (
            <div style={{ marginBottom: 42 }}>
            <strong>Select Size</strong>

            <div style={{ display: "flex", gap: "clamp(8px, 2vw, 14px)", marginTop: 14, flexWrap: "wrap" }}>
                {product.variants.map((variant) => {
                const price = prices[variant.stripePriceId]
                const cached = cachedPrices[variant.stripePriceId]?.unit_amount ?? null

                return (
                    <button
                    key={variant.id}
                    onClick={() => setSelectedVariantId(variant.id)}
                    style={{
                        padding: "clamp(10px, 2vw, 14px) clamp(14px, 3vw, 22px)",
                        borderRadius: 999,
                        border:
                        variant.id === selectedVariantId
                            ? "2px solid #000"
                            : "1px solid #ddd",
                        background: "#fff",
                        cursor: "pointer",
                        minWidth: "clamp(100px, 15vw, 130px)",
                    }}
                    >
                    <div style={{ fontWeight: 500, fontSize: "clamp(14px, 1.5vw, 16px)" }}>{variant.label}</div>
                    <div style={{ fontSize: 14, color: "#777" }}>
                        {loadingPrices && cached
                        ? `$${(cached / 100).toFixed(2)}`
                        : loadingPrices || !price
                        ? "—"
                        : `$${(price / 100).toFixed(2)}`}
                    </div>
                    </button>
                )
                })}
            </div>
            </div>
        )}

          {/* ADD */}
        <button
            disabled={!selectedVariant || !selectedPrice || loadingPrices}
            onClick={handleAdd}
            style={{
            width: "100%",
            padding: "20px",
            borderRadius: 999,
            background: "#000",
            color: "#fff",
            fontSize: 14,
            letterSpacing: "0.24em",
            textTransform: "uppercase",
            cursor: "pointer",
            }}
        >
            {product.variants.length === 0 ? (
            "Coming Soon"
            ) : loadingPrices ? (
            "Loading…"
            ) : !Object.keys(prices).length ? (
            "Unavailable"
            ) : (
            `Add to cart — $${selectedPrice ? (selectedPrice / 100).toFixed(2) : "—"}`
            )}
        </button>
        </div>
    </div>

      {/* INFO */}
    <section
        style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
        gap: "clamp(24px, 5vw, 64px)",
        }}
    >
        {hasFlavor && (
        <InfoCard icon="🍃" label="Flavor Profile" title="Flavor Notes">
            <ul style={{ listStyle: "none", padding: 0 }}>
            {content.flavorProfile!.map((note) => (
                <li key={note}>• {note}</li>
            ))}
            </ul>
        </InfoCard>
        )}

        {hasEffect && (
        <InfoCard icon="☁️" label="Effect" title="How It Feels">
            <p>{content.effect}</p>
        </InfoCard>
        )}

        {hasBrewing && (
        <InfoCard icon="🍵" label="Brewing" title="How to Brew">
            {content.brewing?.gongfu && (
            <p>
                <strong>Gongfu:</strong> {content.brewing.gongfu}
            </p>
            )}
            {content.brewing?.western && (
            <p>
                <strong>Western:</strong> {content.brewing.western}
            </p>
            )}
        </InfoCard>
        )}
    </section>
    </main>
)
}

/* -------------------------------- */

function InfoCard({
icon,
label,
title,
children,
}: {
icon: string
label: string
title: string
children: React.ReactNode
}) {
return (
    <div
    className="info-card"
    style={{
        background:
        "radial-gradient(900px 480px at 20% -30%, #ffffff 0%, #f6f4ef 60%, #efede7 100%)",
        borderRadius: "clamp(24px, 4vw, 36px)",
        padding: "clamp(32px, 5vw, 64px) clamp(24px, 4vw, 52px)",
        textAlign: "center",
        transition:
        "transform 0.45s cubic-bezier(.22,1,.36,1), box-shadow 0.45s cubic-bezier(.22,1,.36,1)",
        boxShadow: "0 10px 32px rgba(0,0,0,0.04)",
    }}
    >
    <div className="info-card-icon" style={{ fontSize: 34, marginBottom: 18 }}>{icon}</div>

    <p
        style={{
        textTransform: "uppercase",
        letterSpacing: "0.32em",
        fontSize: 11,
        marginBottom: 12,
        color: "#9b978e",
        }}
    >
        {label}
    </p>

    <h3 style={{ fontSize: 26, fontWeight: 500 }}>{title}</h3>

    <div style={{ fontSize: 16, lineHeight: 1.7 }}>{children}</div>
    </div>
)
}
